layout: sidebar
style: light

plugins:
  - jekyll-octicons
  - jekyll-github-metadata
  - jemoji

permalink: /:year/:month/:day/:title/

defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
      type: "posts"
    values:
      layout: "post"


projects:
  sort_by: pushed
  # sort_by options:
  #   - pushed
  #   - stars
  limit: 3
  exclude:
    archived: false
    forks: true
    projects:
    # - repo-name



social_media:
  # behance: your_username
  # dribbble: your_username
  # facebook: your_username
  # hackerrank: your_username
  # instagram: your_username
  # keybase: your_username
  linkedin: anandsambamoorthy
  # mastodon: your_username
  # medium: your_username
  stackoverflow: 6212771
  # telegram: your_username
  twitter: asamba2
  # unsplash: your_username
  # vk: your_username
  website: https://asamba.github.io
  # youtube: your_username

topics:
  - name: Service Mesh - Istio
    web_url: https://istio.io
    image_url: https://istio.io/img/istio-whitelogo-bluebackground-framed.svg

  - name: Continuous Delivery - Jenkins-X
    web_url: https://jenkins-x.io/
    image_url: https://raw.githubusercontent.com/cdfoundation/artwork/master/jenkinsx/stacked/color/jenkinsx-stacked-color.png

  - name: Spring Cloud
    web_url: https://spring.io/projects/spring-cloud
    image_url: https://spring.io//img/spring-by-pivotal-9066b55828deb3c10e27e609af322c40.png
